[profile.default]
solc-version = "0.8.26"
src = "src"
out = "out"
fs_permissions = [{ access = "read", path = "./"}]
gas_reports = ["*"]

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4

[fuzz]
runs = 64
max_test_rejects = 1262144

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
